### ISSUE TITLE
홈페이지 테마가 제대로 적용되지 않고 있습니다.

### ISSUE THREAD

**Issue by BakSulgi** [17-1-SKKU-OSS/116A#2]
해결 방법이 생각나시면 남겨 주세요.

**Comment by hoseung2** [comment]
그냥 한번초기화하죠

**Comment by LJihyun** [comment]
주소값을 인식하지 못하는 거 같애서 추가해주면 되지 않을까요?

**Comment by BakSulgi** [comment]
다른 경로를 통해 다운받은 테마 파일과 기존 적용되있던 테마 파일에 차이가 있어서 따로 다운 받은 테마를 재적용했더니 문제가 해결되었습니다.
