### ISSUE TITLE
몇가지 사항을 수정해봤습니다.

### ISSUE THREAD

**Issue by BakSulgi** [17-1-SKKU-OSS/116A#9]
develop2를 기반으로 개별 항목에서 메뉴 항목이 제대로 표시되지 않던 문제점을 해결했습니다.

또한 각 이미지가 작아서 잘 안보이고, 직접 이미지를 링크 시키면 다시 페이지로 돌아오는 것이 불편하므로 이미지 팝업을 구현하였습니다. (참고 사이트 : http://blog.naver.com/kdeun00/80158174297)

현재 이미지 팝업은 translation과 django introduce 부분에만 적용되어 있습니다. 변경 사항은 헤더 부분의 스크립트 뿐이므로 이 부분만 복사한다면 다른 페이지에도 쉽게 적용할 수 있을 것이라 생각합니다.

변경 사항은 확정된 것이 아니기에 develop 브랜치에 올렸습니다.

**Comment by LJihyun** [comment]
사진 파일이여서 다시 돌아오는 거 맞아요
